export const AGENT_POLICY_MANAGER_ABI = [
  {
    type: "function",
    name: "policyNonce",
    inputs: [{ name: "smartAccount", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createPolicy",
    inputs: [
      {
        name: "params",
        type: "tuple",
        components: [
          { name: "smartAccount", type: "address" },
          { name: "sessionKey", type: "address" },
          { name: "guardian", type: "address" },
          { name: "token", type: "address" },
          { name: "maxPerTx", type: "uint256" },
          { name: "dailyLimit", type: "uint256" },
          { name: "weeklyLimit", type: "uint256" },
          { name: "totalLimit", type: "uint256" },
          { name: "maxQusdcGasPerTx", type: "uint256" },
          { name: "dailyQusdcGasCap", type: "uint256" },
          { name: "validAfter", type: "uint64" },
          { name: "validUntil", type: "uint64" },
          { name: "allowSinglePayment", type: "bool" },
          { name: "allowBatchPayment", type: "bool" },
          { name: "allowPaymentRequest", type: "bool" },
          { name: "allowSubscription", type: "bool" },
          { name: "allowSponsoredGas", type: "bool" },
          { name: "allowQusdcGas", type: "bool" },
          { name: "allowNativeQieFallback", type: "bool" },
          { name: "pauseWhenGasUnavailable", type: "bool" },
          { name: "recipients", type: "address[]" },
        ],
      },
    ],
    outputs: [{ name: "policyId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getPoliciesBySmartAccount",
    inputs: [{ name: "smartAccount", type: "address" }],
    outputs: [{ type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPolicy",
    inputs: [{ name: "policyId", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "smartAccount", type: "address" },
          { name: "owner", type: "address" },
          { name: "sessionKey", type: "address" },
          { name: "guardian", type: "address" },
          { name: "token", type: "address" },
          { name: "maxPerTx", type: "uint256" },
          { name: "dailyLimit", type: "uint256" },
          { name: "weeklyLimit", type: "uint256" },
          { name: "totalLimit", type: "uint256" },
          { name: "spentToday", type: "uint256" },
          { name: "spentThisWeek", type: "uint256" },
          { name: "spentTotal", type: "uint256" },
          { name: "maxQusdcGasPerTx", type: "uint256" },
          { name: "dailyQusdcGasCap", type: "uint256" },
          { name: "spentQusdcGasToday", type: "uint256" },
          { name: "dayWindowStart", type: "uint64" },
          { name: "weekWindowStart", type: "uint64" },
          { name: "gasDayWindowStart", type: "uint64" },
          { name: "validAfter", type: "uint64" },
          { name: "validUntil", type: "uint64" },
          { name: "allowSinglePayment", type: "bool" },
          { name: "allowBatchPayment", type: "bool" },
          { name: "allowPaymentRequest", type: "bool" },
          { name: "allowSubscription", type: "bool" },
          { name: "allowSponsoredGas", type: "bool" },
          { name: "allowQusdcGas", type: "bool" },
          { name: "allowNativeQieFallback", type: "bool" },
          { name: "pauseWhenGasUnavailable", type: "bool" },
          { name: "active", type: "bool" },
          { name: "guardianRevoked", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isRecipientAllowed",
    inputs: [
      { name: "policyId", type: "bytes32" },
      { name: "recipient", type: "address" },
    ],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
] as const;
